### ISSUE TITLE
SSL Certificate problem

### ISSUE THREAD

**Issue by DiogoFilhoDeMorais** [sumup/sumup-ecom-php-sdk#43]
I have an Laravel API configured with:

"php": "^7.3",
"fideloper/proxy": "^4.2",
"fruitcake/laravel-cors": "^2.0",
"guzzlehttp/guzzle": "^7.0.1",
"laravel/framework": "^8.0",
"laravel/sanctum": "^2.15",
"laravel/tinker": "^2.0",
"sumup/sumup-ecom-php-sdk": "^1.1",
"symfony/http-client": "^5.4",
"symfony/mailgun-mailer": "^5.4"

When I request to the Sumup API from my Laravel project the error message shows these lines:

SumUp\Exceptions\SumUpConnectionException: SSL certificate problem: unable to get local issuer certificate in file C:\Projetos\Php\api-laravel-intelligent\vendor\sumup\sumup-ecom-php-sdk\src\SumUp\HttpClients\SumUpCUrlClient.php on line 74

#0 C:\Projetos\Php\api-laravel-intelligent\vendor\sumup\sumup-ecom-php-sdk\src\SumUp\Services\Authorization.php(141): SumUp\HttpClients\SumUpCUrlClient-&gt;send('POST', '/token', Array, Array)
#1 C:\Projetos\Php\api-laravel-intelligent\vendor\sumup\sumup-ecom-php-sdk\src\SumUp\Services\Authorization.php(83): SumUp\Services\Authorization-&gt;getTokenByClientCredentials()
#2 C:\Projetos\Php\api-laravel-intelligent\vendor\sumup\sumup-ecom-php-sdk\src\SumUp\SumUp.php(57): SumUp\Services\Authorization-&gt;getToken()
#3 C:\Projetos\Php\api-laravel-intelligent\app\Http\Controllers\LicenseController.php(17): SumUp\SumUp-&gt;__construct(Array)
#4 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\LicenseController-&gt;payment(Object(Illuminate\Http\Request))
#5 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('payment', Array)
#6 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\LicenseController), 'payment')
#7 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route-&gt;runController()
#8 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Route-&gt;run()
#9 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(103): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
#14 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(55): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter(Object(Illuminate\Http\Request), Object(Closure), 'api', Object(Closure))
#15 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#16 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), 'sanctum')
#18 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\sanctum\src\Http\Middleware\EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful-&gt;Laravel\Sanctum\Http\Middleware\{closure}(Object(Illuminate\Http\Request))
#20 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\sanctum\src\Http\Middleware\EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#22 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#25 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#27 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#28 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#29 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#34 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\Projetos\Php\api-laravel-intelligent\vendor\fruitcake\laravel-cors\src\HandleCors.php(52): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\Projetos\Php\api-laravel-intelligent\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#51 C:\Projetos\Php\api-laravel-intelligent\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\Projetos\Php\api-laravel-intelligent\public\index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#53 C:\Projetos\Php\api-laravel-intelligent\server.php(21): require_once('C:\\Projetos\\Php...')
#54 {main}
-->

**Comment by arakneaweb** [comment]
Hello ! did you find a solution I got the same issue on a Symfony project :(

**Comment by DBX12** [comment]
Hi,
could you wrap your stack trace in a code block? The `#1` line numbers reference all the other issues in this repository and that's a bit confusing :)
